paths:
  /store/mission:
    post:
      tags:
        - Store
      summary: 미션추가
      parameters:
      - name: mission
        in: body
        required: true
        schema:
          properties:
            store_id:
              type: integer
              description: 가게 ID
              example: 1
            content:
              type: integer
              description: 미션 내용
              example: 10000
            point:
              type: integer
              description: 미션 포인트
              example: 500
      responses:
        '200':
          description: 미션 추가 성공!
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
              data:
                type: object
                example: {
                  "store_id": "1",
                  "content": "10000원 이상 식사",
                  "point": "500p"
                }
                
        '400':
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다

        '500':
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.