paths:
  /store/review:
    post:
      tags:
        - Store
      summary: 리뷰추가
      parameters:
      - name: review
        in: body
        required: true
        schema:
          properties:
            user_id:
              type: integer
              description: 사용자 ID
              example: 1
            store_id:
              type: integer
              description: 가게 ID
              example: 1
            content:
              type: string
              description: 주소
              example: 너무 맛있어요! 진짜 짱이에요!
            grade:
              type: number
              format: float
              description: 평점
              example: 3.5
      responses:
        '200':
          description: 리뷰 추가 성공!
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
              data:
                type: object
                example: {
                  "store_name": "swagger store",
                  "content": "너무 맛있어요! 진짜 짱이에요!",
                  "grade": 3.0
                }
                
        '400':
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다

        '500':
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.