paths:
  /store/add:
    post:
      tags:
        - Store
      summary: 가게추가
      parameters:
      - name: signIn
        in: body
        required: true
        schema:
          properties:
            name:
              type: string
              description: 가게 이름
              example: swagger store
            content:
              type: string
              description: 가게 설명
              example: 한식 전문점
            addr:
              type: string
              description: 주소
              example: 목성시 xx동
            specAddr:
              type: string
              description: 상세 주소
              example: yy번지 3층
            phone:
              type: string
              description: 전화 번호
              example: 02-1234-5678
      responses:
        '200':
          description: 가게 추가 성공!
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
              data:
                type: object
                example: {
                  "phone": "02-1234-5678",
                  "name": "swagger store",
                  "content": "우주 최고의 한식 전문!점"
                }
                
        '400':
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다

        '500':
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.